# Generated by Django 4.2.16 on 2024-10-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='author',
            new_name='autor',
        ),
    ]
