# Generated by Django 4.2.16 on 2024-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_author_comentario_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
