# Generated by Django 4.2.16 on 2024-10-20 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0003_alter_comentario_contenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'permissions': [('puede_eliminar_comentario', 'Puede eliminar comentarios')]},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'permissions': [('puede_editar_publicacion', 'Puede editar publicaciones'), ('puede_eliminar_publicacion', 'Puede eliminar publicaciones')], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.CreateModel(
            name='PerfilColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_colaborador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
