# Generated by Django 4.2.16 on 2024-10-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_comentario_options_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'permissions': [('puede_agregar_publicacion', 'Puede agregar publicaciones'), ('puede_editar_publicacion', 'Puede editar publicaciones'), ('puede_eliminar_publicacion', 'Puede eliminar publicaciones')], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
